server:
  port: 9000


eureka:
  client:
    #向注册中心注册自己
    register-with-eureka: true
    #是否从Eureka server抓取已有的注册信息，默认为true，单节点无所谓，但是集群必须设置true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: zuul #不显示主机名称 actuator微服务的自动配置
    prefer-ip-address: true #访问路径显示ID地址 actuator微服务的自动配置

spring:
  application:
    name: zuul


zuul:
  routes:
    myzuul: #网关名称
      path: /myzuul/**
#      url: http://localhost:8001/payment/insert
      service-id: CLOUD-PROVIDER-PAYMENT-SERVICE
  host:
    connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000   #socket超时
#  servlet-path:

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

logging:
  level:
    org.springframework.web: trace