server:
  port: 8001

spring:
  application:
    name: cloud-provider-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://47.99.193.37/online-exam?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

mybatis:
  #mapperLocation: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities



