server:
  port: 80

spring:
  application:
    name: cloud-customer-order


eureka:
  client:
    #向注册中心注册自己
    register-with-eureka: false
    #是否从Eureka server抓取已有的注册信息，默认为true，单节点无所谓，但是集群必须设置true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/
  instance:
    instance-id: order_feign80 #不显示主机名称 actuator微服务的自动配置
    prefer-ip-address: true #访问路径显示ID地址 actuator微服务的自动配置

#可以使用default给所有的@FeignClient配置
#否则的话使用feignName给特定的@FeignClient进行配置
#feign:
#  client:
#    config:
#      default:
#        conncetTimeout: 5000
#        readTimeout: 5000

#ribbon默认超时时长为1s
ribbon:
  # 指的是建立连接所用的时间,适用于网络状态正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000