server:
  port: 80

spring:
  application:
    name: cloud-customer-order


eureka:
  client:
    #向注册中心注册自己
    register-with-eureka: true
    #是否从Eureka server抓取已有的注册信息，默认为true，单节点无所谓，但是集群必须设置true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/
  instance:
    instance-id: order80 #不显示主机名称 actuator微服务的自动配置
    prefer-ip-address: true #访问路径显示ID地址 actuator微服务的自动配置
